export type AppRole = 'employee' | 'team_lead' | 'finance' | 'admin' | 'developer';
export type SubmissionCurrency = 'INR' | 'USD' | 'EUR' | 'GBP' | 'AED';

export type CreateLineItemInput = {
  creator_id?: string | null;
  brand_id?: string | null;
  deliverable_id?: string | null;
  creator_name?: string | null;
  brand_name?: string | null;
  deliverable_name?: string | null;
  amount?: number | string | null;
  line_order?: number | null;
};

export type CreateSubmissionInput = {
  previous_submission_id?: string | null;
  submitted_at?: string | null;
  business_line?: 'TM' | 'IM' | string | null;
  entry_type?: 'SC' | 'MC' | null;
  entity_type?: 'Agency' | 'Brand' | string | null;
  client_type?: 'Indian' | 'Foreign' | string | null;
  agency_brand_name?: string;
  agency_brand_trade_name?: string | null;
  email_address?: string;
  gst_number?: string | null;
  address?: string | null;
  bill_due?: string;
  invoice_type?: string;
  deliverables?: string | null;
  creator_creators_name?: string | null;
  brand_name?: string | null;
  campaign_code?: string | null;
  campaign_name?: string | null;
  campaign_brand?: string | null;
  campaign_notes?: string | null;
  currency?: SubmissionCurrency | null;
  commercials?: number | string | null;
  additional_information?: string | null;
  additional_agency_commission?: number | string | null;
  reimbursement_amount?: number | string | null;
  reimbursement_receipts?: string | null;
  line_items?: CreateLineItemInput[];
};

export type AppUser = {
  id: string;
  supabase_auth_id: string;
  email: string;
  role: AppRole;
  status: 'active' | 'inactive';
};

export type SanitizedSubmissionPayload = {
  previous_submission_id: string | null;
  submitted_at: string;
  agency_brand_name: string;
  agency_brand_trade_name: string | null;
  email_address: string;
  gst_number: string | null;
  address: string | null;
  bill_due: string;
  invoice_type: string;
  deliverables: string | null;
  creator_creators_name: string | null;
  brand_name: string | null;
  campaign_code: string | null;
  campaign_name: string | null;
  campaign_brand: string | null;
  campaign_notes: string | null;
  currency: SubmissionCurrency;
  commercials: number;
  additional_information: string | null;
  additional_agency_commission: number;
  reimbursement_amount: number;
  reimbursement_receipts: string | null;
  business_line: string | null;
  entry_type: 'SC' | 'MC' | null;
  entity_type: string | null;
  client_type: string | null;
  agency_name: string | null;
  agency_trade_name: string | null;
  brand_trade_name: string | null;
  intake_status: 'submitted';
  sync_status: 'pending_sheet_sync';
  invoice_status: 'Invoice Pending' | 'Invoice created' | 'Po Created/Estimate' | 'Invoice Cancelled' | 'Debit Note' | 'Invoice + Debit Note';
  invoice_number: null;
  debit_note_number: null;
  payment_received: null;
  payment_received_status: 'pending';
  invoice_via_creators_received: null;
  payment_made: null;
  payment_made_status: 'pending';
  closed: null;
  closure_status: 'open';
  reviewed_by: null;
  reviewed_at: null;
  rejection_note: null;
  proforma_invoice?: string | null;
};

export type SanitizedLineItemPayload = {
  creator_id: string | null;
  brand_id: string | null;
  deliverable_id: string | null;
  creator_name: string | null;
  brand_name: string | null;
  deliverable_name: string | null;
  amount: number;
  line_order: number;
};
