-- Atomic recurring follow-up reminder delivery.
--
-- Rollback:
--   drop function if exists public.send_due_follow_up_reminders(integer, integer);
--   drop index if exists public.notifications_follow_up_reminder_cycle_uidx;
--
-- Safety notes:
-- - Existing notification and follow-up rows are not modified by this migration.
-- - The unique index applies only to the new deterministic reminder target paths
--   generated by this function, so historical follow_up_pending duplicates do not
--   block deployment.
-- - Each function call runs in one PostgreSQL transaction. Any insert or update
--   error rolls back the reminder notifications and schedule advancement together.

create unique index if not exists notifications_follow_up_reminder_cycle_uidx
on public.notifications (
  user_id,
  related_submission_id,
  target_path
)
where type = 'follow_up_pending'
  and target_path like '/dashboard/follow-ups?%reminder_cycle=%';

create or replace function public.send_due_follow_up_reminders(
  p_interval_days integer,
  p_limit integer default 100
)
returns table (
  follow_ups_claimed integer,
  notifications_ready integer,
  follow_ups_advanced integer
)
language plpgsql
security definer
set search_path = public
as $fn$
begin
  if p_interval_days is null or p_interval_days < 1 then
    raise exception 'p_interval_days must be at least 1';
  end if;

  if p_limit is null or p_limit < 1 then
    raise exception 'p_limit must be at least 1';
  end if;

  return query
  with locked_follow_ups as materialized (
    select
      f.id,
      f.submission_id,
      f.follow_up_type,
      f.assigned_employee_id,
      f.assigned_team_lead_id,
      f.next_notification_at,
      f.created_at,
      s.proforma_invoice,
      s.agency_brand_name
    from public.follow_ups f
    join public.intake_submissions s on s.id = f.submission_id
    where f.status = 'pending'
      and (f.next_notification_at is null or f.next_notification_at <= timezone('utc', now()))
    order by f.next_notification_at nulls first, f.created_at, f.id
    limit p_limit
    for update of f skip locked
  ),
  recipient_rows as (
    select
      f.id as follow_up_id,
      f.submission_id,
      f.assigned_employee_id as user_id,
      'employee'::public.user_role as role_target,
      case
        when f.follow_up_type = 'payment_received_pending' then 'Bill Due follow-up pending'
        else 'GST follow-up pending'
      end as title,
      case
        when f.follow_up_type = 'payment_received_pending'
          then coalesce(nullif(f.proforma_invoice, ''), 'No PI Required') || ' for ' || coalesce(nullif(f.agency_brand_name, ''), 'submission') || ' is overdue for bill due follow-up.'
        else coalesce(nullif(f.proforma_invoice, ''), 'No PI Required') || ' for ' || coalesce(nullif(f.agency_brand_name, ''), 'submission') || ' still needs GST follow-up.'
      end as message,
      '/dashboard/follow-ups?submission_id=' || f.submission_id::text ||
        '&follow_up_id=' || f.id::text ||
        '&reminder_cycle=' || to_char(coalesce(f.next_notification_at, f.created_at) at time zone 'utc', 'YYYYMMDDHH24MISS') as target_path
    from locked_follow_ups f
    join public.users recipient
      on recipient.id = f.assigned_employee_id
     and recipient.role = 'employee'
     and recipient.status = 'active'

    union all

    select
      f.id as follow_up_id,
      f.submission_id,
      f.assigned_team_lead_id as user_id,
      'team_lead'::public.user_role as role_target,
      case
        when f.follow_up_type = 'payment_received_pending' then 'Bill Due follow-up pending'
        else 'GST follow-up pending'
      end as title,
      case
        when f.follow_up_type = 'payment_received_pending'
          then coalesce(nullif(f.proforma_invoice, ''), 'No PI Required') || ' for ' || coalesce(nullif(f.agency_brand_name, ''), 'submission') || ' is overdue for bill due follow-up.'
        else coalesce(nullif(f.proforma_invoice, ''), 'No PI Required') || ' for ' || coalesce(nullif(f.agency_brand_name, ''), 'submission') || ' still needs GST follow-up.'
      end as message,
      '/dashboard/follow-ups?submission_id=' || f.submission_id::text ||
        '&follow_up_id=' || f.id::text ||
        '&reminder_cycle=' || to_char(coalesce(f.next_notification_at, f.created_at) at time zone 'utc', 'YYYYMMDDHH24MISS') as target_path
    from locked_follow_ups f
    join public.users recipient
      on recipient.id = f.assigned_team_lead_id
     and recipient.role = 'team_lead'
     and recipient.status = 'active'
    where f.assigned_team_lead_id is not null
  ),
  inserted_notifications as (
    insert into public.notifications (
      user_id,
      role_target,
      type,
      title,
      message,
      related_submission_id,
      related_review_id,
      target_path
    )
    select
      r.user_id,
      r.role_target,
      'follow_up_pending'::public.notification_type_enum,
      r.title,
      r.message,
      r.submission_id,
      null::uuid,
      r.target_path
    from recipient_rows r
    on conflict do nothing
    returning user_id, related_submission_id, target_path
  ),
  required_recipient_counts as (
    select follow_up_id, count(*) as required_count
    from recipient_rows
    group by follow_up_id
  ),
  available_notification_keys as (
    select user_id, related_submission_id, target_path
    from inserted_notifications

    union

    select n.user_id, n.related_submission_id, n.target_path
    from public.notifications n
    join recipient_rows r
      on n.user_id = r.user_id
     and n.related_submission_id = r.submission_id
     and n.target_path = r.target_path
     and n.type = 'follow_up_pending'
  ),
  available_notification_counts as (
    select r.follow_up_id, count(k.user_id) as available_count
    from recipient_rows r
    left join available_notification_keys k
      on k.user_id = r.user_id
     and k.related_submission_id = r.submission_id
     and k.target_path = r.target_path
    group by r.follow_up_id
  ),
  ready_follow_ups as (
    select required.follow_up_id
    from required_recipient_counts required
    join available_notification_counts available on available.follow_up_id = required.follow_up_id
    where available.available_count = required.required_count
  ),
  advanced_follow_ups as (
    update public.follow_ups f
    set
      last_notified_at = timezone('utc', now()),
      next_notification_at = timezone('utc', now()) + make_interval(days => p_interval_days),
      updated_at = timezone('utc', now())
    where f.id in (select follow_up_id from ready_follow_ups)
    returning f.id
  )
  select
    (select count(*)::integer from locked_follow_ups),
    (select count(*)::integer from inserted_notifications),
    (select count(*)::integer from advanced_follow_ups);
end;
$fn$;

revoke execute on function public.send_due_follow_up_reminders(integer, integer) from public;
revoke execute on function public.send_due_follow_up_reminders(integer, integer) from anon;
revoke execute on function public.send_due_follow_up_reminders(integer, integer) from authenticated;
grant execute on function public.send_due_follow_up_reminders(integer, integer) to service_role;
